import Joi from 'joi';

export const productValidation = {
  createProduct: Joi.object({
    name: Joi.string().max(255).required(),
    slug: Joi.string().max(255).optional(),
    sku: Joi.string().max(100).required(),
    shortDescription: Joi.string().allow('', null).optional(),
    description: Joi.string().allow('', null).optional(),
    status: Joi.string().valid('draft', 'active', 'archived', 'deleted').default('draft'),
    visibility: Joi.string().valid('public', 'private', 'hidden').default('public'),
    brand: Joi.string().max(100).allow('', null).optional(),
    category: Joi.string().max(100).allow('', null).optional(),
    price: Joi.number().min(0).required(),
    comparePrice: Joi.number().min(0).allow(null).optional(),
    cost: Joi.number().min(0).allow(null).optional(),
    weight: Joi.number().min(0).allow(null).optional(),
    dimensions: Joi.string().max(100).allow('', null).optional(),
    barcode: Joi.string().max(100).allow('', null).optional(),
    taxClass: Joi.string().max(50).allow('', null).optional(),
    seoTitle: Joi.string().max(255).allow('', null).optional(),
    seoDescription: Joi.string().max(500).allow('', null).optional(),
    seoKeywords: Joi.string().max(255).allow('', null).optional(),
    canonicalUrl: Joi.string().max(2048).allow('', null).optional(),
    mediaIds: Joi.array().items(Joi.number().integer().positive()).optional(),
  }),

  updateProduct: Joi.object({
    name: Joi.string().max(255).optional(),
    slug: Joi.string().max(255).optional(),
    sku: Joi.string().max(100).optional(),
    shortDescription: Joi.string().allow('', null).optional(),
    description: Joi.string().allow('', null).optional(),
    status: Joi.string().valid('draft', 'active', 'archived', 'deleted').optional(),
    visibility: Joi.string().valid('public', 'private', 'hidden').optional(),
    brand: Joi.string().max(100).allow('', null).optional(),
    category: Joi.string().max(100).allow('', null).optional(),
    price: Joi.number().min(0).optional(),
    comparePrice: Joi.number().min(0).allow(null).optional(),
    cost: Joi.number().min(0).allow(null).optional(),
    weight: Joi.number().min(0).allow(null).optional(),
    dimensions: Joi.string().max(100).allow('', null).optional(),
    barcode: Joi.string().max(100).allow('', null).optional(),
    taxClass: Joi.string().max(50).allow('', null).optional(),
    seoTitle: Joi.string().max(255).allow('', null).optional(),
    seoDescription: Joi.string().max(500).allow('', null).optional(),
    seoKeywords: Joi.string().max(255).allow('', null).optional(),
    canonicalUrl: Joi.string().max(2048).allow('', null).optional(),
    mediaIds: Joi.array().items(Joi.number().integer().positive()).optional(),
  }),

  listProducts: Joi.object({
    page: Joi.number().integer().min(1).default(1),
    limit: Joi.number().integer().min(1).max(100).default(10),
    search: Joi.string().allow('').optional(),
    status: Joi.string().valid('draft', 'active', 'archived', 'deleted').optional(),
    visibility: Joi.string().valid('public', 'private', 'hidden').optional(),
    category: Joi.string().allow('').optional(),
  }),
};
